# Generated by Django 4.2.3 on 2023-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butterflyuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
