# Generated by Django 4.2.3 on 2023-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
