# Generated by Django 4.2.3 on 2023-08-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('participation_reason', models.TextField()),
                ('equipment', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ANIMALS', 'Animals'), ('ENVIRONMENT', 'Environment'), ('HEALTHCARE', 'Healthcare'), ('SOCIETY', 'Society'), ('OTHER', 'Other')])),
                ('suitable_for', models.CharField(choices=[('KIDS', 'Kids'), ('TEENAGERS', 'Teenagers'), ('ADULTS', 'Adults'), ('ELDERLY', 'Elderly'), ('DISABLED_PEOPLE', 'Disabled people')])),
                ('region', models.CharField(choices=[('BULGARIA', 'Bulgaria'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('BURGAS', 'Burgas'), ('VARNA', 'Varna'), ('VELIKO_TARNOVO', 'Veliko Turnovo'), ('VIDIN', 'Vidin'), ('VRATSA', 'Vratsa'), ('GABROVO', 'Gabrovo'), ('DOBRICH', 'Dobrich'), ('KARDZHALI', 'Kurdzhali'), ('KYUSTENDIL', 'Kyustendil'), ('LOVECH', 'Lovech'), ('MONTANA', 'Montana'), ('PAZARDZHIK', 'Pazardzhik'), ('PERNIK', 'Pernik'), ('PLEVEN', 'Pleven'), ('PLOVDIV', 'Plovdiv'), ('RAZGRAD', 'Razgrad'), ('RUSSE', 'Ruse'), ('SILISTRA', 'Silistra'), ('SLIVEN', 'Sliven'), ('SMOLYAN', 'Smolyan'), ('SOFIA', 'Sofia - city'), ('SOFIA_OBLAST', 'Sofia - region'), ('STARA_ZAGORA', 'Stara Zagora'), ('TARGOVISHTE', 'Turgovishte'), ('HASKOVO', 'Haskovo'), ('SHUMEN', 'Shumen'), ('YAMBOL', 'Yambol')])),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_of_publication',),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiatives.initiative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
