# Generated by Django 4.2.3 on 2023-08-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_participation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiative',
            options={'ordering': ('-date_of_publication',)},
        ),
    ]
