# Generated by Django 4.2.3 on 2023-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_alter_initiative_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='category',
            field=models.CharField(choices=[('Animals', 'Animals'), ('Environment', 'Environment'), ('Healthcare', 'Healthcare'), ('Society', 'Society'), ('Other', 'Other')]),
        ),
    ]
