# Generated by Django 4.2.3 on 2023-08-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_alter_initiative_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ('user',)},
        ),
    ]
