# Generated by Django 4.2.3 on 2023-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0006_alter_initiative_user_alter_participation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='category',
            field=models.CharField(choices=[('Animals', 'ANIMALS'), ('Environment', 'ENVIRONMENT'), ('Healthcare', 'HEALTHCARE'), ('Society', 'SOCIETY'), ('Other', 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='region',
            field=models.CharField(choices=[('Bulgaria', 'BULGARIA'), ('Blagoevgrad', 'BLAGOEVGRAD'), ('Burgas', 'BURGAS'), ('Varna', 'VARNA'), ('Veliko Turnovo', 'VELIKO_TARNOVO'), ('Vidin', 'VIDIN'), ('Vratsa', 'VRATSA'), ('Gabrovo', 'GABROVO'), ('Dobrich', 'DOBRICH'), ('Kurdzhali', 'KARDZHALI'), ('Kyustendil', 'KYUSTENDIL'), ('Lovech', 'LOVECH'), ('Montana', 'MONTANA'), ('Pazardzhik', 'PAZARDZHIK'), ('Pernik', 'PERNIK'), ('Pleven', 'PLEVEN'), ('Plovdiv', 'PLOVDIV'), ('Razgrad', 'RAZGRAD'), ('Ruse', 'RUSSE'), ('Silistra', 'SILISTRA'), ('Sliven', 'SLIVEN'), ('Smolyan', 'SMOLYAN'), ('Sofia - city', 'SOFIA'), ('Sofia - region', 'SOFIA_OBLAST'), ('Stara Zagora', 'STARA_ZAGORA'), ('Turgovishte', 'TARGOVISHTE'), ('Haskovo', 'HASKOVO'), ('Shumen', 'SHUMEN'), ('Yambol', 'YAMBOL')]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='suitable_for',
            field=models.CharField(choices=[('Kids', 'KIDS'), ('Teenagers', 'TEENAGERS'), ('Adults', 'ADULTS'), ('Elderly', 'ELDERLY'), ('Disabled people', 'DISABLED_PEOPLE')]),
        ),
    ]
