# Generated by Django 4.2.3 on 2023-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0007_alter_initiative_category_alter_initiative_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='suitable_for',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('TEENAGERS', 'Teenagers'), ('ADULTS', 'Adults'), ('ELDERLY', 'Elderly'), ('DISABLED_PEOPLE', 'Disabled people')]),
        ),
    ]
