# Generated by Django 4.2.3 on 2023-08-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0008_alter_initiative_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='category',
            field=models.CharField(choices=[('ANIMALS', 'Animals'), ('ENVIRONMENT', 'Environment'), ('HEALTHCARE', 'Healthcare'), ('SOCIETY', 'Society'), ('OTHER', 'Other')]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='region',
            field=models.CharField(choices=[('BULGARIA', 'Bulgaria'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('BURGAS', 'Burgas'), ('VARNA', 'Varna'), ('VELIKO_TARNOVO', 'Veliko Turnovo'), ('VIDIN', 'Vidin'), ('VRATSA', 'Vratsa'), ('GABROVO', 'Gabrovo'), ('DOBRICH', 'Dobrich'), ('KARDZHALI', 'Kurdzhali'), ('KYUSTENDIL', 'Kyustendil'), ('LOVECH', 'Lovech'), ('MONTANA', 'Montana'), ('PAZARDZHIK', 'Pazardzhik'), ('PERNIK', 'Pernik'), ('PLEVEN', 'Pleven'), ('PLOVDIV', 'Plovdiv'), ('RAZGRAD', 'Razgrad'), ('RUSSE', 'Ruse'), ('SILISTRA', 'Silistra'), ('SLIVEN', 'Sliven'), ('SMOLYAN', 'Smolyan'), ('SOFIA', 'Sofia - city'), ('SOFIA_OBLAST', 'Sofia - region'), ('STARA_ZAGORA', 'Stara Zagora'), ('TARGOVISHTE', 'Turgovishte'), ('HASKOVO', 'Haskovo'), ('SHUMEN', 'Shumen'), ('YAMBOL', 'Yambol')]),
        ),
    ]
